server:
  port: 8763  
spring:
  application:
    name: WELLCOME-API
  boot:
    admin:
      client:
        url: http://localhost:8762/  
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
       
management:
  endpoints:
    web:
      exposure:
        include: '*'