server:
  port: 3333
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: one
        uri: lb://WELLCOME-API
        predicates:
        - Path=/wellcome
      - id: two
        uri: lb://GREET-API
        predicates:
        - Path=/greet
          
          
  main:
    web-application-type: reactive