
server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ganesh9879/Spring_Config_Server.git
          clone-on-start: true
management:
  security:
    enabled:false